import React from "react";

const Browse = () => {
  // List of car companies
  const carCompanies = [
    "ABT",
    "AC Schnitzer",
    "Acura",
    "Alfa Romeo",
    "Alpina",
    "Alpine",
    "Apex",
    "Arrinera",
    "Artega",
    "Ascari",
    "Aston Martin",
    "Audi",
    "BAC",
    "BAIC",
    "BMW",
    "Bentley",
    "Bertone",
    "Borgward",
    "Brabham",
    "Brabus",
    "Breckland",
    "Bugatti",
    "Buick",
    "Cadillac",
    "Caparo",
    "Carlsson",
    "Caterham",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Covini",
    "Cupra",
    "Czinger",
    "DS",
    "Dacia",
    "Daewoo",
    "Daihatsu",
    "Daimler",
    "Datsun",
    "De Tomaso",
    "Devon",
    "Dodge",
    "Donkervoort",
    "EDAG",
    "Edo",
    "Elfin",
    "Eterniti",
    "FM Auto",
    "FPV",
    "Farbio",
    "Ferrari",
    "Fiat",
    "Fisker",
    "Ford",
    "GAC",
    "GM",
    "GMC",
    "GTA",
    "Geely",
    "Genesis",
    "Gordon Murray",
    "Gumpert",
    "HSV",
    "Hamann",
    "Hennessey",
    "Holden",
    "Honda",
    "Hummer",
    "Hyundai",
    "Icona",
    "Infiniti",
    "Isuzu",
    "Italdesign",
    "Iveco",
    "Jaguar",
    "Jeep",
    "KTM",
    "Karma",
    "Kia",
    "Kleemann",
    "Koenigsegg",
    "LCC",
    "Lada",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "Larte",
    "Leblanc",
    "Lexus",
    "Lincoln",
    "Lobini",
    "Loremo",
    "Lotus",
    "Lucid",
    "Lynk Co",
    "MG",
    "Mahindra",
    "Mansory",
    "Marcos",
    "Maserati",
    "Maybach",
    "Mazda",
    "Mazel",
    "McLaren",
    "Mercedes-Benz",
    "Mercury",
    "Mindset",
    "Mini",
    "Mitsubishi",
    "Mitsuoka",
    "Morgan",
    "NanoFlowcell",
    "Nilu",
    "Nismo",
    "Nissan",
    "Noble",
    "ORCA",
    "Oldsmobile",
    "Opel",
    "PGO",
    "Pagani",
    "Panoz",
    "Peugeot",
    "Pininfarina",
    "Plymouth",
    "Polestar",
    "Pontiac",
    "Porsche",
    "Proton",
    "Qoros",
    "Ram",
    "Renault",
    "Rimac",
    "Rinspeed",
    "Rivian",
    "Rolls-Royce",
    "Rover",
    "Saab",
    "Saleen",
    "Saturn",
    "Scion",
    "Scout",
    "Seat",
    "Singer",
    "Skoda",
    "Smart",
    "Sony",
    "Spada",
    "Spyker",
    "SsangYong",
    "Startech",
    "Stola",
    "Strosek",
    "StudioTorino",
    "Subaru",
    "Suzuki",
    "TVR",
    "TWR",
    "Tata",
    "TechArt",
    "Tesla",
    "Think",
    "Touring",
    "Toyota",
    "Tramontana",
    "Valmet",
    "Vauxhall",
    "Venturi",
    "VinFast",
    "Volkswagen",
    "Volvo",
    "Vuhl",
    "Wald",
    "Wiesmann",
    "Yes",
    "Zagato",
    "Zenvo",
  ];

  return (
    <div className="min-h-screen bg-gray-900 text-gray-200 mt-15 p-6">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-4xl font-bold text-center text-yellow-400 mb-8">
          Browse Car Companies
        </h1>
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
          {carCompanies.map((company, index) => (
            <button
              key={index}
              className="bg-gray-800 hover:bg-gray-700 text-gray-200 font-semibold py-3 px-4 rounded-lg shadow-md transition-all duration-300 transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-yellow-400"
            >
              {company}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Browse;
